title: 321 Make! facilitator guide to using our paths
hero_image: images/banner.png
description: A guide for facilitators using our 321 Make! paths of projects. 
version: 4
listed: false
copyedit: false
last_tested: "2022-05-09"
steps: 
  - title: Introduction
  - title: Why 321 Make! ?
  - title: What is a path?
  - title: Three Explore projects
  - title: Reflection
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
  - title: Two Design projects
  - title: One Invent project
  - title: Make! projects
  - title: What next?
